### ISSUE TITLE
Вопрос2. Тесты падают с ошибкой

### ISSUE THREAD

**Issue by anna270892** [anna270892/diplom#2]
Я думаю я неправильно запускаю джар-файл с базой mysql, но не уверена, возможно в зависимостях ошибки.

**Запуск:**
**1.Запущен докер:**
CONTAINER ID   IMAGE                COMMAND                  CREATED      STATUS          PORTS                               NAMES            
0ea2b086ea1c   diplom-nodejs        "docker-entrypoint.s…"   5 days ago   Up 32 minutes   0.0.0.0:9999->9999/tcp              diplom-nodejs-1  
44eabe7d10a5   postgres:12-alpine   "docker-entrypoint.s…"   5 days ago   Up 32 minutes   0.0.0.0:5432->5432/tcp              diplom-postgres-1
3b2ac3e3429d   mysql:8.0.18         "docker-entrypoint.s…"   5 days ago   Up 32 minutes   0.0.0.0:3306->3306/tcp, 33060/tcp   diplom-mysql-1   
111571e2da96   nginx                "/docker-entrypoint.…"   5 days ago   Up 31 minutes   80/tcp                              some-nginx   

**2.Запускаю джар-файл с базой mysql:**
java -jar ./artifacts/aqa-shop.jar -port=8080 \ -url=jdbc:mysql://localhost:3306/app \ -user=app \ -password=pass

**3.Запускаю тесты**

**Ошибка:**
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Jan 14, 2024 3:45:37 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find CDP implementation matching 120
Jan 14, 2024 3:45:37 PM org.openqa.selenium.chromium.ChromiumDriver lambda$new$5
WARNING: Unable to find version of CDP to use for 120.0.6099.217. You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.11.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
SQL exception in clearDB

unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=120.0.6099.217)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.20'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [2ccaafbdf36fa86a085c7b9a1cd06c0b, get {url=http://localhost:8080}]
selenide.url: http://localhost:8080
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 120.0.6099.217, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: C:\Users\akoch\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:56030}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:56030/devtoo..., se:cdpVersion: 120.0.6099.217, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
selenide.baseUrl: http://localhost:8080
Session ID: 2ccaafbdf36fa86a085c7b9a1cd06c0b
org.openqa.selenium.WebDriverException: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=120.0.6099.217)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.20'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [2ccaafbdf36fa86a085c7b9a1cd06c0b, get {url=http://localhost:8080}]
selenide.url: http://localhost:8080
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 120.0.6099.217, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: C:\Users\akoch\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:56030}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:56030/devtoo..., se:cdpVersion: 120.0.6099.217, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
selenide.baseUrl: http://localhost:8080
Session ID: 2ccaafbdf36fa86a085c7b9a1cd06c0b

![Screenshot_402](https://github.com/anna270892/diplom/assets/142071185/0c1185b8-e14e-4c5e-801a-1568b34f21c6)

**Comment by andrew-pahomov** [comment]
Покажите терминал с запущенным джарником

**Comment by anna270892** [comment]
во вложении
![Screenshot_403](https://github.com/anna270892/diplom/assets/142071185/724d130e-aa46-49fe-82c7-353f4ae99140)

**Comment by andrew-pahomov** [comment]
Использование параметров командной строки -port, -userp, -password не имеет смысла. Приложение их не знает. Более того, по умолчанию джарник запускается а порту 8080, незачем его сообщать дополнительно. Логин и пароль пользователя для подключения к базе данных подтянется из application.properties, также не нужно их указывать.         
Для указания url базы данных можно использовать параметр -Dspring.datasource.url, -url приложению не знаком.   
Слеши из команды надо убрать, они там точно лишние.

**Comment by anna270892** [comment]
попробовала не работает
![Screenshot_404](https://github.com/anna270892/diplom/assets/142071185/65bce29f-cd26-4400-bb8e-06bdc903cbe1)
