### ISSUE TITLE
Вопрос3. Тесты падают с ошибкой

### ISSUE THREAD

**Issue by anna270892** [anna270892/diplom#3]
Не понимаю почему такая ошибка при запуске тестов, не могу разобраться.
![Screenshot_405](https://github.com/anna270892/diplom/assets/142071185/680ce398-3643-4faa-b18b-00440346eff9)

![Screenshot_407](https://github.com/anna270892/diplom/assets/142071185/0b7e7a4f-6e24-403f-b9dc-37d8577ae2c6)

мой запущенный джар-файл на базе mysql
![Screenshot_406](https://github.com/anna270892/diplom/assets/142071185/087d895c-8425-4f44-99b1-834b6a3e6a9c)

**Comment by andrew-pahomov** [comment]
Не вижу на скринах каким образом запускались автотесты.
